# -*- coding: utf-8 -*-
"""halo_dunia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qXB1eK09LXda-R6916CxlOMeNJcdPOYS
"""

print("Halo Dunia !")